### ISSUE TITLE
Failed to load the love-ide package

### ISSUE THREAD

**Issue by K0IN** [rameshvarun/love-ide#18]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: K0IN
**Thrown From**: [love-ide](https://github.com/rameshvarun/love-ide) package, v0.10.0
### Stack Trace

Failed to load the love-ide package

```
At Cannot find module 'log4js'

Error: Cannot find module 'log4js'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\julian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\julian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:/Users/julian/.atom/packages/love-ide-master/lib/main.js:4:42)
    at Module._compile (C:\Users\julian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\julian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\julian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\julian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at C:\Users\julian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\julian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\julian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\julian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\julian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\julian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\julian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\julian\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:743:28
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by rameshvarun** [comment]
Are you still having this issue? If uninstalling / reinstalling love-ide doesn't work, you can try cd'ing into `C:/Users/julian/.atom/packages/love-ide-master/` and running `npm install`. This may at least tell us why `log4js` isn't being loaded.

**Comment by rameshvarun** [comment]
I've removed log4js in 3097c540858263181c1e80d9fafc543b1b1b0052, so this shouldn't be a problem anymore.
