### ISSUE TITLE
console not displaying when launching with love-ide:run-love

### ISSUE THREAD

**Issue by kxait** [rameshvarun/love-ide#20]

**Comment by rameshvarun** [comment]
What OS are you on? Have you selected a terminal emulator from the package settings?

**Comment by TaylorAnderson** [comment]
I'm also having this problem.  I'm working on Windows and chose the CMD terminal from the package settings

**Comment by josephknight** [comment]
Also having this problem on Mac using iTerm2 in settings. Also, the built-in Terminal app is not available as a choice.

**Comment by thedaemon** [comment]
[Enter steps to reproduce:]

1. Select iTerm from settings
2. press auto run

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [love-ide](https://github.com/rameshvarun/love-ide) package 0.17.0


### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/brandonayers/.atom/packages/love-ide/lib/main.js:64

TypeError: Cannot read property 'getPath' of undefined
    at /packages/love-ide/lib/main.js:64:30
    at Array.sort (native)
    at run (/packages/love-ide/lib/main.js:63:7)
    at executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:112:5)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:70:7)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-glsl 0.2.3 
autocomplete-love 0.4.0 
busy-signal 1.4.3 
chester-atom-syntax 0.2.0 
gaia-dark-syntax 2.0.0 
github-atom-light-syntax 0.5.0 
hyperclick 0.0.40 
hyperclick-love 0.6.0 
intentions 1.1.2 
language-glsl 2.0.1 
language-lua 0.9.11 
linter 2.2.0 
linter-luaparse 0.2.0 
linter-ui-default 1.6.1 
love-ide 0.17.0 
solarized-dark-ui 0.3.2 
solarized-light-ui 0.1.0 
solarized-one-light-ui 1.10.4 
spacegray-light-neue-ui 0.1.7 
tool-bar 1.1.0 
```

**Comment by hasen6** [comment]
So this never got solved basically?

**Comment by Zetrious** [comment]
It doesn't output like simple things like print.

**Comment by SebastienBellanger** [comment]
I had the same problem on Windows with CMD selected, and changing the love executable from love.exe to lovec.exe worked for me!
