### ISSUE TITLE
Failed to activate the love-ide package

### ISSUE THREAD

**Issue by 4aiman** [rameshvarun/love-ide#27]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Debian GNU/Linux
**Thrown From**: [love-ide](https://github.com/rameshvarun/love-ide) package 0.17.0

### Stack Trace

Failed to activate the love-ide package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (usr/share/atom/resources/app/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/packages/love-ide/lib/main.js:47:2)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:253:25)
    at /usr/share/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:645:40)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:519:35
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -0:29 core:backspace (input.hidden-input)
     -0:26 core:confirm (input.hidden-input)
     -0:05.2.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:04.7.0 core:delete (input.hidden-input)
```

### Non-Core Packages

```
love-ide 0.17.0 
```

**Comment by becauseimgray** [comment]
Also having this issue. It happened when I installed the love-ide package through Atom's install pane.

**Comment by programmer757** [comment]
i am having trouble getting the directory straight with lua so I can use atom thanks can you please help? its on my desktop not in c im not sure how to get it in c so if you can help me with this that would be great im using windows
